server:
  port: 9598

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.105:5432/kilid_db
    username: postgres
    password: behdad2012



  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false




minio:
  bucket:
    name: kilid
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

  url: http://127.0.0.1:9000






management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    tags:
      application: MonitoringKrdSpringDemoProject